### PR TITLE
Fixed brightness bug

### LINKED ISSUE #63: Fix Theme Switching Bug
When setting your preferred theme to dark and reloading the app, the theme only switches when the drawer is on screen.

### PR DESCRIPTION
**Pull request by DavidTarrab**
Fixed bug where the user's preferred brightness would only change when the drawer was open.
Fixes #63

### CODE REVIEW

File: lib/src/pages/route_initializer.dart [hunk 1]
```diff
@@ -54,6 +54,15 @@ class RouteInitializerState extends State<RouteInitializer> {
...
+
+				final brightness = Services.instance.prefs.brightness;
+				ThemeChanger.of(context).brightness = caseConverter<Brightness> (
+					value: brightness,
+					onTrue: Brightness.light,
+					onFalse: Brightness.dark,
+					onNull: MediaQuery.of(context).platformBrightness,
+				);
+				
 			}
```
Comment (Levi-Lesches) [inline lib/src/pages/route_initializer.dart:66]:
```suggestion

				ThemeChanger.of(context).brightness = caseConverter<Brightness> (
					value: Services.instance.prefs.brightness,
					onTrue: Brightness.light,
					onFalse: Brightness.dark,
					onNull: MediaQuery.of(context).platformBrightness,
				);
			}
```

You can merge the two together like this

**Review by Levi-Lesches — APPROVED** [review]
LGTM

**Review by Levi-Lesches — APPROVED** [review]
Now LGTM
